### ISSUE TITLE
Issues Building the project

### ISSUE THREAD

**Issue by Sean-Hodgson** [LoLlYdE/twitch_lurk_bot#1]
Whenever i try to build the project i get 5 errors from Redis.cs:

Error	CS0161	'Redis.Database.get': not all code paths return a value	
	
Error	CS0201	Only assignment, call, increment, decrement, and new object expressions can be used as a statement

Error	CS1043	{ or ; expected	

Error	CS1513	} expected

Error	CS1513	} expected

**Comment by Lollyde** [comment]
I cant replicate this issue, cloning the repository from scratch and building succeeds for me. 
![image](https://user-images.githubusercontent.com/11347524/46582043-a1245d00-ca41-11e8-8c95-5cc59f308f12.png)

Maybe try cloning it again?

**Comment by Sean-Hodgson** [comment]
I'll try cloning it again, are there any specific program versions that you use that might change it?

**Comment by Lollyde** [comment]
I'm using VS 2017, though that shouldnt make any difference for the apparent syntax errors youre getting

**Comment by Sean-Hodgson** [comment]
Could it be the .net framework im using? I cloned it again and got the same errors

**Comment by Lollyde** [comment]
I have no idea what even could be different, sorry I cant help. maybe just try to fix the errors locally?

**Comment by Sean-Hodgson** [comment]
I reinstalled VS 2017 and the build worked.
